services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      CORS_ORIGIN: "*"
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
        - action: rebuild
          path: ./server/package.json
